# Generated by Django 5.0.14 on 2025-11-28 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order", "คำสั่งซื้อ"),
                            ("payment", "การชำระเงิน"),
                            ("shipping", "การจัดส่ง"),
                            ("review", "รีวิว"),
                            ("system", "ระบบ"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="ประเภท",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="หัวข้อ")),
                ("message", models.TextField(verbose_name="ข้อความ")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="อ่านแล้ว"),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="ลิงก์"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้รับ",
                    ),
                ),
            ],
            options={
                "verbose_name": "การแจ้งเตือน",
                "verbose_name_plural": "การแจ้งเตือน",
                "ordering": ["-created_at"],
            },
        ),
    ]
