# Generated by Django 5.0.14 on 2025-11-28 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่คำสั่งซื้อ"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รอชำระเงิน"),
                            ("paid", "ชำระเงินแล้ว"),
                            ("shipped", "จัดส่งแล้ว"),
                            ("delivered", "ได้รับสินค้าแล้ว"),
                            ("cancelled", "ยกเลิก"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "shipping_name",
                    models.CharField(max_length=100, verbose_name="ชื่อผู้รับ"),
                ),
                (
                    "shipping_phone",
                    models.CharField(max_length=20, verbose_name="เบอร์โทรผู้รับ"),
                ),
                ("shipping_address", models.TextField(verbose_name="ที่อยู่จัดส่ง")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "บัตรเครดิต/เดบิต"),
                            ("bank_transfer", "โอนเงิน"),
                            ("cod", "ชำระเงินปลายทาง"),
                        ],
                        default="cod",
                        max_length=20,
                        verbose_name="วิธีชำระเงิน",
                    ),
                ),
                (
                    "payment_status",
                    models.BooleanField(default=False, verbose_name="ชำระเงินแล้ว"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ยอดรวมสินค้า",
                    ),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ค่าจัดส่ง",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ยอดรวมทั้งหมด",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="หมายเหตุ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="อัพเดทเมื่อ"),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ซื้อ",
                    ),
                ),
            ],
            options={
                "verbose_name": "คำสั่งซื้อ",
                "verbose_name_plural": "คำสั่งซื้อ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="ชื่อสินค้า"),
                ),
                (
                    "product_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ราคา"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="จำนวน"),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="รวม"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="คำสั่งซื้อ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="products.product",
                        verbose_name="สินค้า",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sold_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ขาย",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการสินค้า",
                "verbose_name_plural": "รายการสินค้า",
            },
        ),
    ]
