# Generated by Django 5.0.14 on 2025-11-28 02:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="คะแนน",
                    ),
                ),
                ("comment", models.TextField(verbose_name="ความคิดเห็น")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="อัพเดทเมื่อ"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                        verbose_name="สินค้า",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้รีวิว",
                    ),
                ),
            ],
            options={
                "verbose_name": "รีวิว",
                "verbose_name_plural": "รีวิว",
                "ordering": ["-created_at"],
                "unique_together": {("product", "user")},
            },
        ),
    ]
