# Generated by Django 5.0.14 on 2025-11-28 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ชื่อหมวดหมู่"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="รายละเอียด"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="รูปภาพ",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="อัพเดทเมื่อ"),
                ),
            ],
            options={
                "verbose_name": "หมวดหมู่",
                "verbose_name_plural": "หมวดหมู่",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ชื่อสินค้า")),
                ("slug", models.SlugField(max_length=200, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="รายละเอียด")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ราคา"
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="จำนวนในสต็อก"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดขาย"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="จำนวนเข้าชม"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="อัพเดทเมื่อ"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                        verbose_name="หมวดหมู่",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ขาย",
                    ),
                ),
            ],
            options={
                "verbose_name": "สินค้า",
                "verbose_name_plural": "สินค้า",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="รูปภาพ"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="รูปหลัก")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ลำดับ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="สินค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "รูปภาพสินค้า",
                "verbose_name_plural": "รูปภาพสินค้า",
                "ordering": ["order", "-is_main"],
            },
        ),
    ]
